[project]
name = "number-guessing-game"
version = "0.1.0"
description = "A simple number guessing game to test your luck."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
]
